[workspace]
resolver = "3"
members = [
    "crates/core",
    "crates/frontend/src-tauri",
]

[workspace.package]
version = "0.3.17"
authors = ["Korbin de Man"]
license = "MIT"
repository = "https://github.com/korbindeman/zinnia"
edition = "2024"
